### ISSUE TITLE
跨进程问题

### ISSUE THREAD

**Issue by yangpeixing** [qingmei2/RxImagePicker#22]
作者貌似不支持跨进程调用，在manifest中配置了单独进程的activity调用知乎样式的图片选择器会闪退，报错
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.qingmei2.sample/com.qingmei2.rximagepicker_extension_zhihu.ui.ZhihuImagePickerActivity}: java.lang.NullPointerException: Attempt to read from field 'int com.qingmei2.rximagepicker_extension.entity.SelectionSpec.themeId' on a null object reference
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2964)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3025)
                                                       at android.app.ActivityThread.-wrap13(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1658)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:177)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6665)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
                                                    Caused by: java.lang.NullPointerException: Attempt to read from field 'int com.qingmei2.rximagepicker_extension.entity.SelectionSpec.themeId' on a null object reference
                                                       at com.qingmei2.rximagepicker_extension_zhihu.ui.ZhihuImagePickerActivity.onCreate(ZhihuImagePickerActivity.java:23)
                                                       at android.app.Activity.performCreate(Activity.java:6748)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1132)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2917)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3025) 
                                                       at android.app.ActivityThread.-wrap13(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1658) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:177) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6665) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)

**Comment by qingmei2** [comment]
@yangpeixing 

感谢您的回复。 👍 

我自己通过实现一个ApplicationB，将Sample的ZhihuActivity通过 intent-filter 暴露出来给ApplicationB，然后通过B打开ZhihuActivity并选择图片，并没有发生问题。

据log来看，是SelectionSpec.themeId报空指针异常，能否您提供对应的代码呢，我将帮助您检查可能遇到的问题。

**Comment by qingmei2** [comment]
因为精力有限，最终个人放弃对库本身提供 【进程间通信】的支持 😢 

如果有感兴趣的朋友，欢迎PR  🙌
