### ISSUE TITLE
使用0.4.0版本，在BaseSystemPickerView类的120行调用onNext方法报NullPointerException

### ISSUE THREAD

**Issue by feimenggo** [qingmei2/RxImagePicker#30]
```
java.lang.RuntimeException: Unable to resume activity {com.mozhe.mzcz/com.mozhe.mzcz.mvp.view.home.book.BookSetupActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=65636, result=0, data=null} to activity {com.mozhe.mzcz/com.mozhe.mzcz.mvp.view.home.book.BookSetupActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.a.n.e.onNext(java.lang.Object)' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3216)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3247)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2582)
	at android.app.ActivityThread.access$1000(ActivityThread.java:166)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1414)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5628)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)
Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=65636, result=0, data=null} to activity {com.mozhe.mzcz/com.mozhe.mzcz.mvp.view.home.book.BookSetupActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.a.n.e.onNext(java.lang.Object)' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3818)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3190)
	... 10 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.a.n.e.onNext(java.lang.Object)' on a null object reference
	at com.c.a.f.b.a(BaseSystemPickerView.java:120)
	at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:156)
	at com.mozhe.mzcz.mvp.view.home.book.BookSetupActivity.onActivityResult(BookSetupActivity.java:183)
	at android.app.Activity.dispatchActivityResult(Activity.java:6524)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3814)
	... 11 more
```

**Comment by qingmei2** [comment]
@feimenggo 

能否加QQ群 391638630呢，方便找出错误原因。

**Comment by qingmei2** [comment]
长时间未回复，关闭issue
