### ISSUE TITLE
点击预览崩溃

### ISSUE THREAD

**Issue by zhangliangnbu** [qingmei2/RxImagePicker#32]
## 场景
1. 使用微信相册UI框架
2. 从相册选择图片，限定只选择一张。当选中一个图片后，再点击该图片预览，崩溃。
3. 这个崩溃并不是每次都会发生，有时候需要反复操作（选中->预览，返回取消，再选中->预览等等）才会发生。有时操作一次就会发生，有时需要操作一二十次才会发生，但终究会发生。
4. 而且这个崩溃只发生在一张图片上，点击其他的图片预览时不会发生这种崩溃，至少目前是这样的。

## 崩溃 stacktrace
``` 
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter object
        at com.qingmei2.rximagepicker_extension.ui.adapter.PreviewPagerAdapter.setPrimaryItem(PreviewPagerAdapter.kt)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1236)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
        at android.view.View.measure(View.java:19857)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
        at android.view.View.measure(View.java:19857)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
        at android.view.View.measure(View.java:19857)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
        at android.view.View.measure(View.java:19857)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:19857)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
        at android.view.View.measure(View.java:19857)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:689)
        at android.view.View.measure(View.java:19857)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2275)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1366)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1619)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
        at android.view.Choreographer.doCallbacks(Choreographer.java:686)
        at android.view.Choreographer.doFrame(Choreographer.java:621)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

## 崩溃前的部分日志信息
是`Bugly`记录并打印的

```
08-14 09:44:53.296 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatAlbumPreviewActivity onPaused <<<
08-14 09:44:53.297 30025-30025/com.xxx.xxxx I/CrashReport-Native: Set native info: isAppForeground(false)
08-14 09:44:53.324 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatImagePickerActivity onResumed <<<
08-14 09:44:53.325 30025-30025/com.xxx.xxxx I/CrashReport-Native: Set native info: isAppForeground(true)
08-14 09:44:53.481 30025-30090/com.xxx.xxxx D/OpenGLRenderer: endAllActiveAnimators on 0x8e2a5700 (AppCompatTextView) with handle 0x8ac651e0
08-14 09:44:53.737 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatAlbumPreviewActivity onDestroyed <<<
08-14 09:44:56.663 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatImagePickerActivity onPaused <<<
08-14 09:44:56.664 30025-30025/com.xxx.xxxx I/CrashReport-Native: Set native info: isAppForeground(false)
08-14 09:44:56.683 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatAlbumPreviewActivity onCreated <<<
08-14 09:44:56.713 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatAlbumPreviewActivity onResumed <<<
08-14 09:44:56.714 30025-30025/com.xxx.xxxx I/CrashReport-Native: Set native info: isAppForeground(true)
08-14 09:44:56.750 30025-30025/com.xxx.xxxx I/ExifInterface_JNI: Raw image not detected
08-14 09:44:56.772 30025-30025/com.xxx.xxxx I/ExifInterface_JNI: Raw image not detected
08-14 09:44:56.798 30025-30025/com.xxx.xxxx I/ExifInterface_JNI: Raw image not detected
08-14 09:44:56.842 30025-30025/com.xxx.xxxx D/ImageViewTouchBase: matrix: { x: 47.25, y: 0.0, scalex: 0.934375, scaley: 0.934375 }
08-14 09:44:56.962 30025-30025/com.xxx.xxxx D/ImageViewTouchBase: matrix: { x: 47.25, y: 0.0, scalex: 0.934375, scaley: 0.934375 }
08-14 09:44:57.046 30025-30025/com.xxx.xxxx D/ImageViewTouchBase: matrix: { x: 47.25, y: 0.0, scalex: 0.934375, scaley: 0.934375 }
08-14 09:44:57.662 30025-30067/com.xxx.xxxx D/CrashReport: [AsyncTaskHandler] Post a normal task: com.tencent.bugly.crashreport.biz.a$2
    Uploading frequency will not be checked if SDK is in debug mode.
08-14 09:44:57.669 30025-30067/com.xxx.xxxx D/CrashReport: [UserInfo] There is no user info in local database.
08-14 09:44:58.494 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatAlbumPreviewActivity onPaused <<<
08-14 09:44:58.495 30025-30025/com.xxx.xxxx I/CrashReport-Native: Set native info: isAppForeground(false)
08-14 09:44:58.516 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatImagePickerActivity onResumed <<<
08-14 09:44:58.517 30025-30025/com.xxx.xxxx I/CrashReport-Native: Set native info: isAppForeground(true)
08-14 09:44:58.893 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatAlbumPreviewActivity onDestroyed <<<
08-14 09:45:00.658 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatImagePickerActivity onPaused <<<
08-14 09:45:00.659 30025-30025/com.xxx.xxxx I/CrashReport-Native: Set native info: isAppForeground(false)
08-14 09:45:00.691 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatAlbumPreviewActivity onCreated <<<
08-14 09:45:00.728 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatAlbumPreviewActivity onResumed <<<
08-14 09:45:00.731 30025-30025/com.xxx.xxxx I/CrashReport-Native: Set native info: isAppForeground(true)
08-14 09:45:00.774 30025-30025/com.xxx.xxxx I/ExifInterface_JNI: Raw image not detected
08-14 09:45:00.803 30025-30025/com.xxx.xxxx I/ExifInterface_JNI: Raw image not detected
08-14 09:45:00.836 30025-30025/com.xxx.xxxx I/ExifInterface_JNI: Raw image not detected
08-14 09:45:00.900 30025-30025/com.xxx.xxxx D/ImageViewTouchBase: matrix: { x: 47.25, y: 0.0, scalex: 0.934375, scaley: 0.934375 }
08-14 09:45:01.016 30025-30025/com.xxx.xxxx D/ImageViewTouchBase: matrix: { x: 47.25, y: 0.0, scalex: 0.934375, scaley: 0.934375 }
08-14 09:45:01.116 30025-30025/com.xxx.xxxx D/ImageViewTouchBase: matrix: { x: 47.25, y: 0.0, scalex: 0.934375, scaley: 0.934375 }
08-14 09:45:02.666 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatAlbumPreviewActivity onPaused <<<
08-14 09:45:02.667 30025-30025/com.xxx.xxxx I/CrashReport-Native: Set native info: isAppForeground(false)
08-14 09:45:02.690 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatImagePickerActivity onResumed <<<
08-14 09:45:02.691 30025-30025/com.xxx.xxxx I/CrashReport-Native: Set native info: isAppForeground(true)
08-14 09:45:03.080 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatAlbumPreviewActivity onDestroyed <<<
08-14 09:45:06.850 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatImagePickerActivity onPaused <<<
08-14 09:45:06.851 30025-30025/com.xxx.xxxx I/CrashReport-Native: Set native info: isAppForeground(false)
08-14 09:45:06.869 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatAlbumPreviewActivity onCreated <<<
08-14 09:45:06.898 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatAlbumPreviewActivity onResumed <<<
08-14 09:45:06.899 30025-30025/com.xxx.xxxx I/CrashReport-Native: Set native info: isAppForeground(true)
08-14 09:45:06.933 30025-30025/com.xxx.xxxx I/ExifInterface_JNI: Raw image not detected
08-14 09:45:06.955 30025-30025/com.xxx.xxxx I/ExifInterface_JNI: Raw image not detected
08-14 09:45:06.978 30025-30025/com.xxx.xxxx I/ExifInterface_JNI: Raw image not detected
08-14 09:45:07.024 30025-30025/com.xxx.xxxx D/ImageViewTouchBase: matrix: { x: 47.25, y: 0.0, scalex: 0.934375, scaley: 0.934375 }
08-14 09:45:07.125 30025-30025/com.xxx.xxxx D/ImageViewTouchBase: matrix: { x: 47.25, y: 0.0, scalex: 0.934375, scaley: 0.934375 }
08-14 09:45:07.226 30025-30025/com.xxx.xxxx D/ImageViewTouchBase: matrix: { x: 47.25, y: 0.0, scalex: 0.934375, scaley: 0.934375 }
08-14 09:45:07.769 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatAlbumPreviewActivity onPaused <<<
08-14 09:45:07.770 30025-30025/com.xxx.xxxx I/CrashReport-Native: Set native info: isAppForeground(false)
08-14 09:45:07.790 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatImagePickerActivity onResumed <<<
08-14 09:45:07.792 30025-30025/com.xxx.xxxx I/CrashReport-Native: Set native info: isAppForeground(true)
08-14 09:45:08.194 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatAlbumPreviewActivity onDestroyed <<<
08-14 09:45:11.821 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatImagePickerActivity onPaused <<<
08-14 09:45:11.822 30025-30025/com.xxx.xxxx I/CrashReport-Native: Set native info: isAppForeground(false)
08-14 09:45:11.846 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatAlbumPreviewActivity onCreated <<<
08-14 09:45:11.878 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatAlbumPreviewActivity onResumed <<<
08-14 09:45:11.879 30025-30025/com.xxx.xxxx I/CrashReport-Native: Set native info: isAppForeground(true)
08-14 09:45:11.920 30025-30025/com.xxx.xxxx I/ExifInterface_JNI: Raw image not detected
08-14 09:45:11.949 30025-30025/com.xxx.xxxx I/ExifInterface_JNI: Raw image not detected
08-14 09:45:11.978 30025-30025/com.xxx.xxxx I/ExifInterface_JNI: Raw image not detected
08-14 09:45:12.039 30025-30025/com.xxx.xxxx D/ImageViewTouchBase: matrix: { x: 47.25, y: 0.0, scalex: 0.934375, scaley: 0.934375 }
08-14 09:45:12.188 30025-30025/com.xxx.xxxx D/ImageViewTouchBase: matrix: { x: 47.25, y: 0.0, scalex: 0.934375, scaley: 0.934375 }
08-14 09:45:12.256 30025-30025/com.xxx.xxxx D/ImageViewTouchBase: matrix: { x: 47.25, y: 0.0, scalex: 0.934375, scaley: 0.934375 }
08-14 09:45:12.884 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatAlbumPreviewActivity onPaused <<<
08-14 09:45:12.885 30025-30025/com.xxx.xxxx I/CrashReport-Native: Set native info: isAppForeground(false)
08-14 09:45:12.905 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatImagePickerActivity onResumed <<<
08-14 09:45:12.907 30025-30025/com.xxx.xxxx I/CrashReport-Native: Set native info: isAppForeground(true)
08-14 09:45:13.293 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatAlbumPreviewActivity onDestroyed <<<
08-14 09:45:14.471 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatImagePickerActivity onPaused <<<
08-14 09:45:14.472 30025-30025/com.xxx.xxxx I/CrashReport-Native: Set native info: isAppForeground(false)
08-14 09:45:14.502 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatAlbumPreviewActivity onCreated <<<
08-14 09:45:14.539 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatAlbumPreviewActivity onResumed <<<
08-14 09:45:14.540 30025-30025/com.xxx.xxxx I/CrashReport-Native: Set native info: isAppForeground(true)
08-14 09:45:14.582 30025-30025/com.xxx.xxxx I/ExifInterface_JNI: Raw image not detected
08-14 09:45:14.604 30025-30025/com.xxx.xxxx I/ExifInterface_JNI: Raw image not detected
08-14 09:45:14.630 30025-30025/com.xxx.xxxx I/ExifInterface_JNI: Raw image not detected
08-14 09:45:14.682 30025-30025/com.xxx.xxxx D/ImageViewTouchBase: matrix: { x: 47.25, y: 0.0, scalex: 0.934375, scaley: 0.934375 }
08-14 09:45:14.781 30025-30025/com.xxx.xxxx D/ImageViewTouchBase: matrix: { x: 47.25, y: 0.0, scalex: 0.934375, scaley: 0.934375 }
08-14 09:45:14.898 30025-30025/com.xxx.xxxx D/ImageViewTouchBase: matrix: { x: 47.25, y: 0.0, scalex: 0.934375, scaley: 0.934375 }
08-14 09:45:15.811 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatAlbumPreviewActivity onPaused <<<
08-14 09:45:15.812 30025-30025/com.xxx.xxxx I/CrashReport-Native: Set native info: isAppForeground(false)
08-14 09:45:15.828 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatImagePickerActivity onResumed <<<
08-14 09:45:15.829 30025-30025/com.xxx.xxxx I/CrashReport-Native: Set native info: isAppForeground(true)
08-14 09:45:16.204 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatAlbumPreviewActivity onDestroyed <<<
08-14 09:45:20.815 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatImagePickerActivity onPaused <<<
08-14 09:45:20.816 30025-30025/com.xxx.xxxx I/CrashReport-Native: Set native info: isAppForeground(false)
08-14 09:45:20.839 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatAlbumPreviewActivity onCreated <<<
08-14 09:45:20.872 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatAlbumPreviewActivity onResumed <<<
08-14 09:45:20.873 30025-30025/com.xxx.xxxx I/CrashReport-Native: Set native info: isAppForeground(true)
08-14 09:45:20.919 30025-30025/com.xxx.xxxx I/ExifInterface_JNI: Raw image not detected
08-14 09:45:20.950 30025-30025/com.xxx.xxxx I/ExifInterface_JNI: Raw image not detected
08-14 09:45:20.979 30025-30025/com.xxx.xxxx I/ExifInterface_JNI: Raw image not detected
08-14 09:45:21.060 30025-30025/com.xxx.xxxx D/ImageViewTouchBase: matrix: { x: 47.25, y: 0.0, scalex: 0.934375, scaley: 0.934375 }
08-14 09:45:21.160 30025-30025/com.xxx.xxxx D/ImageViewTouchBase: matrix: { x: 47.25, y: 0.0, scalex: 0.934375, scaley: 0.934375 }
08-14 09:45:21.227 30025-30025/com.xxx.xxxx D/ImageViewTouchBase: matrix: { x: 47.25, y: 0.0, scalex: 0.934375, scaley: 0.934375 }
08-14 09:45:21.747 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatAlbumPreviewActivity onPaused <<<
08-14 09:45:21.748 30025-30025/com.xxx.xxxx I/CrashReport-Native: Set native info: isAppForeground(false)
08-14 09:45:21.774 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatImagePickerActivity onResumed <<<
08-14 09:45:21.776 30025-30025/com.xxx.xxxx I/CrashReport-Native: Set native info: isAppForeground(true)
08-14 09:45:22.131 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatAlbumPreviewActivity onDestroyed <<<
08-14 09:45:23.581 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatImagePickerActivity onPaused <<<
08-14 09:45:23.582 30025-30025/com.xxx.xxxx I/CrashReport-Native: Set native info: isAppForeground(false)
08-14 09:45:23.601 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatAlbumPreviewActivity onCreated <<<
08-14 09:45:23.633 30025-30025/com.xxx.xxxx D/CrashReport: >>> com.qingmei2.rximagepicker_extension_wechat.ui.WechatAlbumPreviewActivity onResumed <<<
08-14 09:45:23.633 30025-30025/com.xxx.xxxx I/CrashReport-Native: Set native info: isAppForeground(true)
08-14 09:45:23.652 30025-30025/com.xxx.xxxx D/AndroidRuntime: Shutting down VM
```

## 崩溃时手机的使用情况
```
    # CRASH DEVICE: Nexus 6 ROOTED
    # RUNTIME AVAIL RAM:849653760 ROM:25250299904 SD:25250299904
    # RUNTIME TOTAL RAM:3114692608 ROM:27893952512 SD:27893952512
```

## 崩溃发生的图片信息
![image](https://user-images.githubusercontent.com/15187878/44068125-2bdea70a-9fab-11e8-96ca-0c515e081f3d.png)

![291534212293_ pic](https://user-images.githubusercontent.com/15187878/44067832-ee8497ee-9fa9-11e8-9be5-6a19da7f8ae0.jpg)

如有可能，麻烦尽快解决这个Bug

**Comment by qingmei2** [comment]
@zhangliangnbu  谢谢你的反馈和详细的信息，我会最快时间找到并解决这个问题 🤝

**Comment by zhangliangnbu** [comment]
👌

**Comment by zhangliangnbu** [comment]
@qingmei2 可能是我项目的`com.android.support`包版本较低的原因导致的，我升级支持包的版本为`27.1.1`后，操作了几遍，没有出现崩溃。

你的项目里的`com.android.support`包版本是`27.1.1`，而我项目之前的是`27.0.0`，我引入你的依赖的时候，`exclude`掉了你的`com.android.support`包
```
    implementation deps.rx_image_picker_support_wechat,{
        exclude group: 'com.android.support', module: 'appcompat-v7'
        exclude group: 'com.android.support', module: 'recyclerview-v7'
    }
```
你的代码基于高版本支持包，当引用低版本支持库的时候，会出现问题。

`com.qingmei2.rximagepicker_extension.ui.adapter.PreviewPagerAdapter`类中
```
    override fun setPrimaryItem(container: ViewGroup, position: Int, `object`: Any) {
        super.setPrimaryItem(container, position, `object`)
        mListener?.onPrimaryItemSet(position)
    }
```
上面的`object`: Any，在低版本的支持库中，应该是允许空的。因为我升级支持库之后，继承`RecyclerView.Adapter`的类都报编译错误，说是有些方法的参数不能为空，而我之前复写方法的时候是自动加了`?`允空的。忘了说，我也是用`Kotlin`写的代码，上面的崩溃可能仅仅是`Kotlin`语法限制导致的，如果用`Java`，也许就没有这个问题，但没有测试过。

另外说一下，你用的`Android Studio`和一些依赖版本都比较新，这样会出现以下问题
1. 使用旧的`Android Studio`时会导致你的项目克隆到本地后不能正常运行，我昨天就出现了这个问题，我的`Android Studio`是`3.1.3`的，你要求的`Android Plugin Version`是`3.1.4`，导致一直不能加载`SDK`，升级后才解决这个问题。
2. 支持库比较新，会导致一些旧的项目运行你的代码出现问题。

针对这些问题，建议在wiki的常见问题里做一点说明，让大家升级IDE和支持库，这样大家也会少走些弯路。

**Comment by qingmei2** [comment]
@zhangliangnbu  

十分感谢您的反馈，我会重新检查这部分的代码，保证其稳定性。 👍 

> 使用旧的Android Studio时会导致你的项目克隆到本地后不能正常运行

的确，我更倾向于使用最新稳定版本的环境，这可能需要开发者fork后，下载最近稳定版本的AndroidStudio运行源代码。

> 支持库比较新，会导致一些旧的项目运行你的代码出现问题。

正如您所说的，我会在常见问题中添加这个问题。

**再次感谢您的回复，真的帮我个人节省了很多时间！** 🐈

**Comment by zhangliangnbu** [comment]
@qingmei2 🤝🤝
