### ISSUE TITLE
有的机型会报：No Activity found to handle Intent

### ISSUE THREAD

**Issue by feimenggo** [qingmei2/RxImagePicker#33]
`io.reactivex.exceptions.OnErrorNotImplementedException: No Activity found to handle Intent { act=android.intent.action.PICK typ=image/* flg=0x41 (has extras) }
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
	at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
	at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:309)
	at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:229)
	at com.qingmei2.rximagepicker.ui.BaseSystemPickerView.onAttach(BaseSystemPickerView.kt:43)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1372)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5055)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.PICK typ=image/* flg=0x41 (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1632)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1424)
	at android.app.Activity.startActivityForResult(Activity.java:3424)
	at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:68)
	at android.support.v4.app.ActivityCompat.startActivityForResult(ActivityCompat.java:233)
	at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:830)
	at android.support.v4.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:939)
	at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:1021)
	at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:1010)
	at com.qingmei2.rximagepicker.ui.gallery.SystemGalleryPickerView.startRequest(SystemGalleryPickerView.kt:55)
	at com.qingmei2.rximagepicker.ui.BaseSystemPickerView$requestPickImage$1.accept(BaseSystemPickerView.kt:49)
	at com.qingmei2.rximagepicker.ui.BaseSystemPickerView$requestPickImage$1.accept(BaseSystemPickerView.kt:22)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	... 21 more
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.PICK typ=image/* flg=0x41 (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1632)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1424)
	at android.app.Activity.startActivityForResult(Activity.java:3424)
	at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:68)
	at android.support.v4.app.ActivityCompat.startActivityForResult(ActivityCompat.java:233)
	at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:830)
	at android.support.v4.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:939)
	at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:1021)
	at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:1010)
	at com.qingmei2.rximagepicker.ui.gallery.SystemGalleryPickerView.startRequest(SystemGalleryPickerView.kt:55)
	at com.qingmei2.rximagepicker.ui.BaseSystemPickerView$requestPickImage$1.accept(BaseSystemPickerView.kt:49)
	at com.qingmei2.rximagepicker.ui.BaseSystemPickerView$requestPickImage$1.accept(BaseSystemPickerView.kt:22)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:309)
	at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:229)
	at com.qingmei2.rximagepicker.ui.BaseSystemPickerView.onAttach(BaseSystemPickerView.kt:43)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1372)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5055)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
	at dalvik.system.NativeStart.main(Native Method)
`
能不能对这个异常进行捕获处理呢？

**Comment by qingmei2** [comment]
@feimenggo 

机型的原因，可能是设备本身没有提供 android本身系统级别相册 的这个Activity，在onError()中处理即可。

**Comment by feimenggo** [comment]
嗯，谢谢

**Comment by jhchee** [comment]
> @feimenggo
> 
> 机型的原因，可能是设备本身没有提供 android本身系统级别相册 的这个Activity，在onError()中处理即可。

請問此問題該怎麼解決?

**Comment by jhchee** [comment]
@qingmei2 
是否可用如下方法來處理該問題

在次行修改[code](https://github.com/qingmei2/RxImagePicker/blob/f14b921bcb9cc702c85fc5d75ca520ddfa70c1e8/rximagepicker/src/main/java/com/qingmei2/rximagepicker/ui/gallery/BasicGalleryConfig.kt#L43)

```kotlin
            val getIntent = Intent(Intent.ACTION_GET_CONTENT)
            val pickIntent = Intent(Intent.ACTION_PICK)
                .addFlags(Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION)
            val chooserIntent = Intent.createChooser(getIntent, "Select Image")
            chooserIntent.putExtra(Intent.EXTRA_INITIAL_INTENTS, arrayOf(pickIntent))
            chooserIntent.apply {
                putExtra(Intent.EXTRA_LOCAL_ONLY, true)
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
                type = getMimesType()
            }
            return chooserIntent
```

參考[https://stackoverflow.com/a/45707761/7068460](https://stackoverflow.com/a/45707761/7068460)
