### ISSUE TITLE
Demo图片预览BUG

### ISSUE THREAD

**Issue by XuQK** [qingmei2/RxImagePicker#34]
我相册里有两张图，一张83x1291，一张2171x51，知乎和微信两个demo预览是一片黑，左右滑动也滑不动，别的图片正常
```
2018-09-30 15:58:09.926 6104-6205/com.qingmei2.sample W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (1080x16799, max=16384x16384)
```

还有不支持WEBP图片预览啊，虽然实际能预览出来，但是有报错
```
2018-09-30 15:53:44.699 6104-6104/com.qingmei2.sample W/ExifInterface: Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.
    java.io.IOException: Invalid marker: 89
        at android.media.ExifInterface.getJpegAttributes(ExifInterface.java:1846)
        at android.media.ExifInterface.loadAttributes(ExifInterface.java:1475)
        at android.media.ExifInterface.<init>(ExifInterface.java:1112)
        at com.qingmei2.rximagepicker_extension.utils.ExifInterfaceCompat.newInstance(ExifInterfaceCompat.kt:49)
        at com.qingmei2.rximagepicker_extension.utils.PhotoMetadataUtils$Companion.shouldRotate(PhotoMetadataUtils.kt:154)
        at com.qingmei2.rximagepicker_extension.utils.PhotoMetadataUtils$Companion.getBitmapSize(PhotoMetadataUtils.kt:62)
        at com.qingmei2.rximagepicker_extension.ui.PreviewItemFragment.onViewCreated(PreviewItemFragment.kt:62)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1439)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2215)
        at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
        at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
        at android.view.View.measure(View.java:19957)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
        at android.view.View.measure(View.java:19957)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6132)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
        at android.view.View.measure(View.java:19957)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6132)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
        at android.view.View.measure(View.java:19957)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6132)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:19957)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6132)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
        at android.view.View.measure(View.java:19957)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6132)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:855)
        at android.view.View.measure(View.java:19957)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2548)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1628)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1892)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1504)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6983)
2018-09-30 15:53:44.699 6104-6104/com.qingmei2.sample W/ExifInterface:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:883)
        at android.view.Choreographer.doCallbacks(Choreographer.java:689)
        at android.view.Choreographer.doFrame(Choreographer.java:624)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:869)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:159)
        at android.app.ActivityThread.main(ActivityThread.java:6364)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)
```

**Comment by qingmei2** [comment]
目前对长图的加载支持还不够完善，看看之后有没有好的方式能够支持更多格式的图片
