### ISSUE TITLE
大佬  最新版 2.3.0-alpha01 奔溃了 本地库 没事

### ISSUE THREAD

**Issue by deslie2008** [qingmei2/RxImagePicker#37]
*** crash ***
*** time: 11-02 12:41:00.458 ***
*** version: 2.3.0-alpha01/21 ***
*** device: HUAWEI/HUAWEI MT7-CL00/6.0 ***
java.lang.NoClassDefFoundError: Failed resolution of: Lio/reactivex/android/schedulers/AndroidSchedulers;
	at com.qingmei2.rximagepicker.scheduler.RxImagePickerSchedulers.ui(RxImagePickerSchedulers.kt:18)
	at com.qingmei2.rximagepicker.core.ConfigProcessor.process(ConfigProcessor.kt:26)
	at com.qingmei2.rximagepicker.core.ProxyProviders$invoke$1.call(ProxyProviders.kt:23)
	at com.qingmei2.rximagepicker.core.ProxyProviders$invoke$1.call(ProxyProviders.kt:9)
	at io.reactivex.internal.operators.observable.ObservableDefer.subscribeActual(ObservableDefer.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12030)
	at io.reactivex.Observable.blockingFirst(Observable.java:4986)
	at com.qingmei2.rximagepicker.core.ProxyProviders.invoke(ProxyProviders.kt:40)
	at java.lang.reflect.Proxy.invoke(Proxy.java:393)
	at $Proxy3.openGallery(Unknown Source)
	at com.qingmei2.sample.wechat.WechatActivity.openGallery(WechatActivity.java:99)
	at com.qingmei2.sample.wechat.WechatActivity.onPermissionGrant(WechatActivity.java:89)
	at com.qingmei2.sample.wechat.WechatActivity.checkPermissionAndRequest(WechatActivity.java:66)
	at com.qingmei2.sample.wechat.WechatActivity.access$000(WechatActivity.java:26)
	at com.qingmei2.sample.wechat.WechatActivity$2.onClick(WechatActivity.java:54)
	at android.view.View.performClick(View.java:5264)
	at android.view.View$PerformClick.run(View.java:21297)
	at android.os.Handler.handleCallback(Handler.java:743)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:150)
	at android.app.ActivityThread.main(ActivityThread.java:5546)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
Caused by: java.lang.ClassNotFoundException: Didn't find class "io.reactivex.android.schedulers.AndroidSchedulers" on path: DexPathList[[zip file "/data/app/com.qingmei2.sample-1/base.apk", zip file "/data/app/com.qingmei2.sample-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.qingmei2.sample-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.qingmei2.sample-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.qingmei2.sample-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.qingmei2.sample-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.qingmei2.sample-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.qingmei2.sample-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.qingmei2.sample-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.qingmei2.sample-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.qingmei2.sample-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.qingmei2.sample-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.qingmei2.sample-1/lib/arm, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	... 24 more
	Suppressed: java.lang.ClassNotFoundException: io.reactivex.android.schedulers.AndroidSchedulers
		at java.lang.Class.classForName(Native Method)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 25 more
	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

*** crash ***
*** time: 11-02 12:41:02.123 ***
*** version: 2.3.0-alpha01/21 ***
*** device: HUAWEI/HUAWEI MT7-CL00/6.0 ***
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.qingmei2.sample/com.qingmei2.rximagepicker_extension_wechat.ui.WechatImagePickerActivity}: kotlin.KotlinNullPointerException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2444)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2504)
	at android.app.ActivityThread.access$900(ActivityThread.java:165)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:150)
	at android.app.ActivityThread.main(ActivityThread.java:5546)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
Caused by: kotlin.KotlinNullPointerException
	at com.qingmei2.rximagepicker_extension.entity.SelectionSpec$Companion.getInstance(SelectionSpec.kt:127)
	at com.qingmei2.rximagepicker_extension_wechat.ui.WechatImagePickerActivity.onCreate(WechatImagePickerActivity.kt:15)
	at android.app.Activity.performCreate(Activity.java:6367)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2397)
	... 9 more

**Comment by qingmei2** [comment]
@zhengdong1201 

你好，2.3.0版本是为了协助开发者迁移 androidX 的，请问你的项目用的是androidX的相关依赖吗，不是的话请使用2.2.0版本。

![image](https://user-images.githubusercontent.com/21142152/47900258-3dae1380-deb7-11e8-9a9f-7dd69809c333.png)

**Comment by deslie2008** [comment]
@qingmei2  是clone的您的项目

**Comment by qingmei2** [comment]
@zhengdong1201 

> 2.3.0-alpha01 奔溃了 本地库 没事

不好意思，我可能理解出现了偏差，您能仔细描述一下 错误是怎么发生的吗，`本地库没事`又是指？ 🤝

**Comment by 13kmsteady** [comment]
@zhengdong1201 
你好，你直接 clone 项目，运行没有问题。但是在自己的 Demo 中，添加 2.3.0-alpha01 的依赖，是不是就报错了？我能这样理解吗？

**Comment by deslie2008** [comment]
<img width="935" alt="wx20181102-172418 2x" src="https://user-images.githubusercontent.com/16347822/47906453-3e997200-dec4-11e8-88ed-7c9187c968ce.png">
@qingmei2  dependRemote 设置为true就报了上述错了，false没有问题

**Comment by deslie2008** [comment]
@13kmsteady 我是直接跑的大佬的demo

**Comment by qingmei2** [comment]
@zhengdong1201 

谢谢您的回复，有结果了我会第一时间回复您。 👍

**Comment by qingmei2** [comment]
@zhengdong1201 

已确认，是因为bintray插件的问题，导致编译打包aar时依赖没有打进去，目前只有最新版本的2.3.0会出现这个问题，我会尽快修复这个bug

**Comment by qingmei2** [comment]
@zhengdong1201 

该bug已紧急修复，最新修正版本为 `2.3.0-alpha03`，请尝试拉取最新版本的代码，或者将依赖升级至2.3.0-alpha03以避免同样错误的发生（前提是您的项目已经迁移了androidx的支持，否则请继续使用2.2.0的稳定版本）。

再次感谢您百忙之中抽出时间进行反馈！ 😄

> 关于2.3.0-alpha03版本的更多信息，请参考[版本更新日志](https://github.com/qingmei2/RxImagePicker/releases/tag/2.3.0-alpha03)

**Comment by deslie2008** [comment]
@qingmei2 感谢大佬 完结撒花
