### ISSUE TITLE
迁移到AndroidX后，首次拍照正常返回后，跳转到其他页面会出现崩溃

### ISSUE THREAD

**Issue by yuzhiqiang1993** [qingmei2/RxImagePicker#42]
版本：
   implementation"org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.1.0-alpha01'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.0-alpha3'
    implementation 'com.google.android.material:material:1.1.0-alpha02'
    implementation 'com.github.qingmei2:rximagepicker:2.4.1'

使用场景：
在同一个Activity中，第一次打开相机，拍照，正常
再次打开相机，此时已经报错
日志：
` java.lang.IllegalStateException: Failure saving state: active BasicCameraFragment{7999170 (9a42260b-7266-49b4-a844-2ee5c4298dcc)} was removed from the FragmentManager
        at androidx.fragment.app.FragmentManagerImpl.saveAllState(FragmentManagerImpl.java:2315)
        at androidx.fragment.app.FragmentController.saveAllState(FragmentController.java:150)
        at androidx.fragment.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:496)
        at androidx.appcompat.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:511)
        at android.app.Activity.performSaveInstanceState(Activity.java:1537)
        at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1301)
        at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4760)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4073)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4132)
        at android.app.ActivityThread.-wrap25(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1697)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:159)
        at android.app.ActivityThread.main(ActivityThread.java:6385)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)`

**Comment by yuzhiqiang1993** [comment]
同样的，只要是我在正常拍照返回后重新打开任何一个页面，都会出现这个问题。不知道是不是AndroidX库本身的bug

**Comment by yuzhiqiang1993** [comment]
不好意思，确实是AndroidX的问题，将implementation 'androidx.appcompat:appcompat:1.1.0-alpha01'改为1.0.2就没有出现这个问题了。
