### ISSUE TITLE
请教下调用拍照的问题

### ISSUE THREAD

**Issue by sfaker** [qingmei2/RxImagePicker#48]
我只是引用了com.github.qingmei2:rximagepicker:2.4.2的包，在调用拍照的时候出现找不到BasicCameraFragment的问题。如下是我的调用代码：
 picker.openCamera(ModuleJNMapMainActivity.this).subscribe(result -> {
                Glide.with(ModuleJNMapMainActivity.this).load(result.getUri()).into(mBinding.moduleJnMapMainImg);
            });

如下是报错信息：
java.lang.NoClassDefFoundError: com.qingmei2.rximagepicker.ui.camera.BasicCameraFragment
        at libcore.reflect.InternalNames.getClass(InternalNames.java:55)
        at java.lang.Class.getDexCacheType(Class.java:476)
        at libcore.reflect.AnnotationAccess.decodeValue(AnnotationAccess.java:705)
        at libcore.reflect.AnnotationAccess.getDefaultValue(AnnotationAccess.java:361)
        at java.lang.reflect.Method.getDefaultValue(Method.java:327)
        at libcore.reflect.AnnotationFactory.getElementsDescription(AnnotationFactory.java:75)
        at libcore.reflect.AnnotationFactory.<init>(AnnotationFactory.java:112)
        at libcore.reflect.AnnotationFactory.createAnnotation(AnnotationFactory.java:94)
        at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:666)
        at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:641)
        at libcore.reflect.AnnotationAccess.getDeclaredAnnotation(AnnotationAccess.java:170)
        at java.lang.reflect.Method.getAnnotation(Method.java:300)
        at com.qingmei2.rximagepicker.core.ProxyTranslator.streamSourcesFrom(ProxyTranslator.kt:87)
        at com.qingmei2.rximagepicker.core.ProxyTranslator.processMethod(ProxyTranslator.kt:25)
        at com.qingmei2.rximagepicker.core.ProxyProviders$invoke$1.call(ProxyProviders.kt:19)
        at com.qingmei2.rximagepicker.core.ProxyProviders$invoke$1.call(ProxyProviders.kt:9)
        at io.reactivex.internal.operators.observable.ObservableDefer.subscribeActual(ObservableDefer.java:32)
        at io.reactivex.Observable.subscribe(Observable.java:12030)
        at io.reactivex.Observable.blockingFirst(Observable.java:4986)
        at com.qingmei2.rximagepicker.core.ProxyProviders.invoke(ProxyProviders.kt:40)
        at java.lang.reflect.Proxy.invoke(Proxy.java:393)
        at com.chinadci.yongy.jn_map.ui.main.$Proxy0.openCamera(Unknown Source)
        at com.chinadci.yongy.jn_map.ui.main.ModuleJNMapMainActivity$ModuleJNMapClick.goToCameraInterface(ModuleJNMapMainActivity.java:487)
        at com.chinadci.yongy.jn_map.databinding.ActivityModuleJnMapMainBinding._internalCallbackOnClick(ActivityModuleJnMapMainBinding.java:645)
        at android.databinding.generated.callback.OnClickListener.onClick(OnClickListener.java:11)
        at android.view.View.performClick(View.java:5275)
        at android.view.View$PerformClick.run(View.java:21559)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5845)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.qingmei2.rximagepicker.ui.camera.BasicCameraFragment" on path: DexPathList[[zip file "/data/app/com.chinadci.yongy.jn_tel_dcimbs-2/base.apk"],nativeLibraryDirectories=[/data/app/com.chinadci.yongy.jn_tel_dcimbs-2/lib/arm, /data/app/com.chinadci.yongy.jn_tel_dcimbs-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at libcore.reflect.InternalNames.getClass(InternalNames.java:53)
        at java.lang.Class.getDexCacheType(Class.java:476) 
        at libcore.reflect.AnnotationAccess.decodeValue(AnnotationAccess.java:705) 
        at libcore.reflect.AnnotationAccess.getDefaultValue(AnnotationAccess.java:361) 
        at java.lang.reflect.Method.getDefaultValue(Method.java:327) 
        at libcore.reflect.AnnotationFactory.getElementsDescription(AnnotationFactory.java:75) 
        at libcore.reflect.AnnotationFactory.<init>(AnnotationFactory.java:112) 
        at libcore.reflect.AnnotationFactory.createAnnotation(AnnotationFactory.java:94) 
        at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:666) 
        at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:641) 
        at libcore.reflect.AnnotationAccess.getDeclaredAnnotation(AnnotationAccess.java:170) 
        at java.lang.reflect.Method.getAnnotation(Method.java:300) 
        at com.qingmei2.rximagepicker.core.ProxyTranslator.streamSourcesFrom(ProxyTranslator.kt:87) 
        at com.qingmei2.rximagepicker.core.ProxyTranslator.processMethod(ProxyTranslator.kt:25) 
        at com.qingmei2.rximagepicker.core.ProxyProviders$invoke$1.call(ProxyProviders.kt:19) 
        at com.qingmei2.rximagepicker.core.ProxyProviders$invoke$1.call(ProxyProviders.kt:9) 
        at io.reactivex.internal.operators.observable.ObservableDefer.subscribeActual(ObservableDefer.java:32) 
        at io.reactivex.Observable.subscribe(Observable.java:12030) 
        at io.reactivex.Observable.blockingFirst(Observable.java:4986) 
        at com.qingmei2.rximagepicker.core.ProxyProviders.invoke(ProxyProviders.kt:40) 
        at java.lang.reflect.Proxy.invoke(Proxy.java:393) 
        at com.chinadci.yongy.jn_map.ui.main.$Proxy0.openCamera(Unknown Source) 
        at com.chinadci.yongy.jn_map.ui.main.ModuleJNMapMainActivity$ModuleJNMapClick.goToCameraInterface(ModuleJNMapMainActivity.java:487) 
        at com.chinadci.yongy.jn_map.databinding.ActivityModuleJnMapMainBinding._internalCallbackOnClick(ActivityModuleJnMapMainBinding.java:645) 
        at android.databinding.generated.callback.OnClickListener.onClick(OnClickListener.java:11) 
        at android.view.View.performClick(View.java:5275) 
        at android.view.View$PerformClick.run(View.java:21559) 
        at android.os.Handler.handleCallback(Handler.java:815) 
        at android.os.Handler.dispatchMessage(Handler.java:104) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:5845) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768) 
    	Suppressed: java.lang.NoClassDefFoundError: com.qingmei2.rximagepicker.ui.camera.BasicCameraFragment
        at dalvik.system.DexFile.defineClassNative(Native Method)
        at dalvik.system.DexFile.defineClass(DexFile.java:226)
        at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
        at dalvik.system.DexPathList.findClass(DexPathList.java:338)
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
        		... 36 more
    	Suppressed: java.lang.ClassNotFoundException: com.qingmei2.rximagepicker.ui.camera.BasicCameraFragment
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
    		at java.

**Comment by qingmei2** [comment]
@sfaker 

收到，我会尽快针对这个情况进行调查.

**Comment by sfaker** [comment]
希望可以尽快找到问题所在，最近要用到这个功能又刚好看到这个库，觉得构思很好，所以想用在项目上

**Comment by qingmei2** [comment]
@sfaker 

嗯嗯，请问你的项目迁移AndroidX了吗？

**Comment by sfaker** [comment]
@qingmei2 
迁移了

**Comment by sfaker** [comment]
@qingmei2 
不好意思，我没看到那句android X才能用2.4.2版本的，现在版本换回来没有问题了，谢谢！

**Comment by qingmei2** [comment]
@sfaker 

好的，那我就把issue关闭了哈 🤝
