### ISSUE TITLE
依赖调用报错

### ISSUE THREAD

**Issue by CaiJinFu** [qingmei2/RxImagePicker#53]
2019-04-18 12:32:14.907 1457-8001/? E/ActivityTrigger: activityStartTrigger: not whiteListedcom.xincaidong.mergerbridge/com.qingmei2.rximagepicker_extension_wechat.ui.WechatImagePickerActivity/1
2019-04-18 12:32:14.908 1457-8001/? E/ActivityTrigger: activityResumeTrigger: not whiteListedcom.xincaidong.mergerbridge/com.qingmei2.rximagepicker_extension_wechat.ui.WechatImagePickerActivity/1
2019-04-18 12:32:14.909 683-713/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
2019-04-18 12:32:14.931 1457-4351/? E/ActivityTrigger: activityResumeTrigger: not whiteListedcom.xincaidong.mergerbridge/com.qingmei2.rximagepicker_extension_wechat.ui.WechatImagePickerActivity/1
2019-04-18 12:32:15.338 10484-10484/com.xincaidong.mergerbridge E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xincaidong.mergerbridge, PID: 10484
    android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class com.xincaidong.mergerbridge.library.imagepicker.ui.widget.WechatMediaGrid
    Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class com.xincaidong.mergerbridge.library.imagepicker.ui.widget.WechatMediaGrid
    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.xincaidong.mergerbridge.library.imagepicker.ui.widget.WechatMediaGrid" on path: DexPathList[[zip file "/data/app/com.xincaidong.mergerbridge-WgXm0M8f2738jOP_pmsUpw==/base.apk"],nativeLibraryDirectories=[/data/app/com.xincaidong.mergerbridge-WgXm0M8f2738jOP_pmsUpw==/lib/arm64, /data/app/com.xincaidong.mergerbridge-WgXm0M8f2738jOP_pmsUpw==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:168)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.view.LayoutInflater.createView(LayoutInflater.java:610)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:496)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
        at com.qingmei2.rximagepicker_extension.ui.adapter.AlbumMediaAdapter.onCreateViewHolder(AlbumMediaAdapter.kt:70)
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6794)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5975)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
        at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:557)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
        at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:171)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
        at android.view.View.layout(View.java:20729)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20729)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20729)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
        at android.view.View.layout(View.java:20729)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20729)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20729)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
2019-04-18 12:32:15.339 10484-10484/com.xincaidong.mergerbridge E/AndroidRuntime:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20729)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20729)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20729)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:757)
        at android.view.View.layout(View.java:20729)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2857)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2384)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1524)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7396)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1065)
        at android.view.Choreographer.doCallbacks(Choreographer.java:877)
        at android.view.Choreographer.doFrame(Choreographer.java:808)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1051)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
2019-04-18 12:32:15.455 2523-2594/? E/octvm_klo: open /data/system/dropbox/system_app_crash@1554862500760.txt for read error, No such file or directory
2019-04-18 12:32:15.456 2523-2594/? E/octvm_klo: read: Unexpected EOF!
2019-04-18 12:32:15.514 1457-1714/? E/InputDispatcher: channel '98f0746 com.xincaidong.mergerbridge/com.xincaidong.mergerbridge.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2019-04-18 12:32:15.538 1457-1714/? E/InputDispatcher: channel '168586e com.xincaidong.mergerbridge/com.xincaidong.mergerbridge.ui.home.LauncherActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2019-04-18 12:32:15.538 1457-1714/? E/InputDispatcher: channel '54657ad com.xincaidong.mergerbridge/com.qingmei2.rximagepicker_extension_wechat.ui.WechatImagePickerActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

我的依赖：
    //图片选择框架
    implementation 'com.github.qingmei2:rximagepicker:2.4.2'
    // 提供了自定义UI图片选择器的基本组件，自定义UI的需求需要添加该依赖
    implementation 'com.github.qingmei2:rximagepicker_support:2.4.2'
    // WeChat picture selector
    implementation 'com.github.qingmei2:rximagepicker_support_wechat:2.4.2'

调用：
WechatImagePicker imagePicker = RxImagePicker.create(WechatImagePicker.class);
                    imagePicker
                        .openGallery(
                            this,
                            new WechatConfigrationBuilder(MimeType.INSTANCE.ofImage(), false)
                                .maxSelectable(9)
                                .countable(true)
                                .spanCount(4)
                                .countable(false)
                                .build())
                        .subscribe(
                            new Consumer<Result>() {
                              @Override
                              public void accept(Result result) {
                                Log.i(TAG, "onViewClicked: " + result.getUri().getPath());
                                // 做您想做的，比如将选取的图片展示在ImageView中
                                //                                GlideApp.with(this)
                                //                                        .load(result.getUri())
                                //                                        .into(imageView);
                              }
                            });

这集成真是花费了我好多时间，还是没有成功，有点蛋疼了兄弟

**Comment by qingmei2** [comment]
@CaiJingFu 

请问你升级AndroidX了嘛

**Comment by qingmei2** [comment]
@CaiJingFu 

请先尝试下载源码，看看能否编译通过并成功运行，因为源码中sample就是依赖的远程库，我跑过测试代码，是可以的，可能需要你确认一下

**Comment by CaiJinFu** [comment]
升级了，demo跑的没问题的。找到原因了，是依赖glide的问题，我依赖的4.9.0的，所以发生了错误。

**Comment by CaiJinFu** [comment]
还有一个问题，因为我想改UI，所以我将demo中微信图片选择的库中的代码全部复制到我的项目中，我项目是用Java写的，但是引用的时候没有问题，编译可以通过，就是在运行的时候，提示找不到。比如RxImagePickerWechatThemeLibraryGlideModule这个类，调用的时候编译可以通过，但是运行起来就会报错。错误: 找不到符号
符号: 类 RxImagePickerWechatThemeLibraryGlideModule
位置: 类 MainActivity
怎么解决？

**Comment by qingmei2** [comment]
如果是把库中代码全部引入到项目中，直接把这个Library中相关的`RxImagePickerWechatThemeLibraryGlideModule`类以及引用删除，直接使用自己项目本身的GlideApp进行图片加载即可。

**Comment by CaiJinFu** [comment]
我把rximagepicker_support_wechat下的代码都复制进了我的项目中，编译是没有问题的，但是运行起来就会提示，找不到WechatImagePickerActivity和WechatImagePickerFragment。

还有我通过
`  //图片选择框架
    implementation 'com.github.qingmei2:rximagepicker:2.4.2'
    // 提供了自定义UI图片选择器的基本组件，自定义UI的需求需要添加该依赖
    implementation 'com.github.qingmei2:rximagepicker_support:2.4.2'
    // WeChat picture selector
    implementation 'com.github.qingmei2:rximagepicker_support_wechat:2.4.2'`
引入了你的库之后，我的APP名字怎么就变成了rximagepicker_extension_wechat

**Comment by qingmei2** [comment]
> 引入了你的库之后，我的APP名字怎么就变成了rximagepicker_extension_wechat

![image](https://user-images.githubusercontent.com/21142152/56343652-e7772780-61ed-11e9-984d-1f41ebf6b1c6.png)

修改（或者移除）一下string.xml文件里面的string即可。

> 但是运行起来就会提示，找不到WechatImagePickerActivity和WechatImagePickerFragment。

这个可能是项目配置的问题，具体来说我也不清楚了，还是自己好好检查一遍看看是不是包名弄错了或者什么～ 🤝

**Comment by CaiJinFu** [comment]
找不到类的原因找到了，在每个class的前面加上open就可以了。怪不得总是提示我找不到该类。如果不是怕风险，我也尝试用KT写公司项目了。

**Comment by qingmei2** [comment]
@CaiJingFu 

那我就把issue关闭了 :tada:
