### ISSUE TITLE
微信主题预览 6张图片，点击使用报 OOM

### ISSUE THREAD

**Issue by 13kmsteady** [qingmei2/RxImagePicker#6]
#### 1. 选择微信主题，点击相册按钮，进入**相册选取界面**

![album_selection](https://user-images.githubusercontent.com/25281383/40540042-4ecc96d8-6049-11e8-9287-9fc749a0f446.jpg)

#### 2. 选择 6 张图片，点击预览，进入 **预览界面**

![preview](https://user-images.githubusercontent.com/25281383/40540059-6395de58-6049-11e8-8b0b-aace67928cdc.jpg)

#### 3. 点击 **预览界面** 的使用按钮，程序发生闪退。以下为错误日志
```java
05-25 18:30:54.067 5083-5083/com.qingmei2.sample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.qingmei2.sample, PID: 5083
    java.lang.OutOfMemoryError: Failed to allocate a 71663628 byte allocation with 16768896 free bytes and 53MB until OOM
        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
        at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
        at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:639)
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:615)
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:653)
        at android.provider.MediaStore$Images$Media.getBitmap(MediaStore.java:867)
        at com.qingmei2.rximagepicker.funtions.ObserverAsConverter$2.subscribe(ObserverAsConverter.java:80)
        at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
        at io.reactivex.Observable.subscribe(Observable.java:11040)
        at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.subscribeInner(ObservableFlatMap.java:162)
        at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:139)
        at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:261)
        at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:182)
        at com.qingmei2.rximagepicker.core.ActivityPickerProjector.emitUri(ActivityPickerProjector.java:62)
        at com.qingmei2.rximagepicker_extension_wechat.ui.WechatImagePickerFragment.onActivityResult(WechatImagePickerFragment.java:290)
        at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:156)
        at android.app.Activity.dispatchActivityResult(Activity.java:6562)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:3768)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:3815)
        at android.app.ActivityThread.access$1500(ActivityThread.java:154)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5571)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
```
### 图片大小及尺寸
| 序号 | 大小（M） | 尺寸（px）|
| :--: | :--: | :--: |
| 1 |  2 | 4272 x 2848 |
| 2 | 5.75 | 5184 x 3456 |
| 3 | 3.62 | 3495 x 5236 |
| 4 | 4.69 | 4000 x 5217 |
| 5 | 1.97 | 3456 x 5184 |
| 6 | 3.03 | 5184 x 3888 |

### 手机
型号：红米 3s
内存：2 + 16 
系统：Android 6.0.1

**Comment by qingmei2** [comment]
OOM原因应该是Bitmap所占的内存太大了。

这是严重的bug，我会尽快修正这个bug并发布下一个版本。

**Comment by qingmei2** [comment]
已修正。

问题发生的原因在于，0.3.0版本之前的@**AsBitmap**处理逻辑，将Uri转换为Bitmap时，并未进行压缩处理。这样会导致在多选图片时，过多的图片短时间同时转换为Bitmap对象，导致OOM的发生。

@**AsBitmap**和@**AsFile**有着导致程序 **不可控行为** 发生的可能性，这个情况在 **基础库** 中并未凸显出来，随着拓展库的增加，这个问题愈发暴露出来。

以@**AsBitmap** 为例，这个注解会标记返回值为Bitmap类型，但是当用户在 **知乎主题UI界面** 点击选择 某个 **视频文件** 时，这可能会导致程序的 **崩溃** 。

这是有临时的解决方案的，比如可以建议开发者 在这种情况下仅配置 @**AsUri**注解，但是这毫无意义，一个有 **限制性** 的API意味着 架构设计的不足。

因此我考虑再三决定移除 该注解，修正后的版本（After 0.3.0），RxImagePicker都将默认返回Uri类型的数据，这样避免OOM的同时，方便开发者轻松处理不同类型的文件（image/video等等）。

遇到该问题的同学请尽快升级V0.3.0,更详细的调整请参考 [更新日志]（https://github.com/qingmei2/RxImagePicker/wiki/ChangeLog/#0.3.0）
