### ISSUE TITLE
Android 10 - 调用imagePicker.openGallery即崩溃

### ISSUE THREAD

**Issue by cocomikes** [qingmei2/RxImagePicker#76]
在Android 9上面运行很好，今天升级到Android 10后，再选择图片APP就Crash了。
分析日志发现报错发生在AlbumLoader里，设置的PROJECTION有误？ **Invalid column COUNT(*) AS count**

附抓取日志如下

**Comment by cocomikes** [comment]
`2019-11-18 22:55:47.154 27946-28186/com.qmi.miaoyu.android E/AndroidRuntime: FATAL EXCEPTION: ModernAsyncTask #1
    Process: com.qmi.miaoyu.android, PID: 27946
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at androidx.loader.content.ModernAsyncTask$3.done(ModernAsyncTask.java:164)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.IllegalArgumentException: Invalid column COUNT(*) AS count
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:437)
        at android.content.ContentResolver.query(ContentResolver.java:962)
        at android.content.ContentResolver.query(ContentResolver.java:890)
        at androidx.core.content.ContentResolverCompat.query(ContentResolverCompat.java:81)
        at androidx.loader.content.CursorLoader.loadInBackground(CursorLoader.java:63)
        at com.qingmei2.rximagepicker_extension.loader.AlbumLoader.loadInBackground(AlbumLoader.kt:35)
        at com.qingmei2.rximagepicker_extension.loader.AlbumLoader.loadInBackground(AlbumLoader.kt:32)
        at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
        at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
2019-11-18 22:55:47.155 27946-28186/com.qmi.miaoyu.android E/CustomActivityOnCrash: App has crashed, executing CustomActivityOnCrash's UncaughtExceptionHandler
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at androidx.loader.content.ModernAsyncTask$3.done(ModernAsyncTask.java:164)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
   ###   Caused by: java.lang.IllegalArgumentException: Invalid column COUNT(*) AS count
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:437)
        at android.content.ContentResolver.query(ContentResolver.java:962)
        at android.content.ContentResolver.query(ContentResolver.java:890)
        at androidx.core.content.ContentResolverCompat.query(ContentResolverCompat.java:81)
        at androidx.loader.content.CursorLoader.loadInBackground(CursorLoader.java:63)
        at com.qingmei2.rximagepicker_extension.loader.AlbumLoader.loadInBackground(AlbumLoader.kt:35)
        at com.qingmei2.rximagepicker_extension.loader.AlbumLoader.loadInBackground(AlbumLoader.kt:32)
        at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
        at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919)

**Comment by cocomikes** [comment]
遇到此问题的同学，请参考 https://github.com/zhihu/Matisse/blob/master/matisse/src/main/java/com/zhihu/matisse/internal/loader/AlbumLoader.java  手动拷贝rximagepicker源码到项目中解决。

**Comment by qingmei2** [comment]
@cocomikes 

谢谢你的反馈，这两天我把bug解决一下，本周更新下版本

**Comment by cocomikes** [comment]
@qingmei2 感谢及时回复。 兼容android Q我已修复， 主要修改了AlbumLoader 、Album，稍后提交一个pull request?

**Comment by qingmei2** [comment]
@cocomikes 

太棒了！期待你的PR！:tada:

**Comment by qingmei2** [comment]
@cocomikes 

谢谢你的PR，我已经合并到了2.x的分支上，本周发布2.5.2（and 3.x）之后会自动close这个issue.

**Comment by qingmei2** [comment]
@cocomikes 

版本已经更新啦(2.x & 3.x)，感谢你的贡献！ 

[更新日志](https://github.com/qingmei2/RxImagePicker/releases)  🎉
