### ISSUE TITLE
 Unable to start activity 后台收集到崩溃日志，内容如下：有没有谁也遇到过该问题？

### ISSUE THREAD

**Issue by diswy** [qingmei2/RxImagePicker#86]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zuoyouxue.student.phone/com.qingmei2.rximagepicker_extension_zhihu.ui.ZhihuImagePickerActivity}: kotlin.KotlinNullPointerException
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2517)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577)
    at android.app.ActivityThread.access$1000(ActivityThread.java:166)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1414)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5619)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)
Caused by: kotlin.KotlinNullPointerException
    at com.qingmei2.rximagepicker_extension.entity.SelectionSpec$Companion.getInstance(SelectionSpec.java:0)
    at com.qingmei2.rximagepicker_extension_zhihu.ui.ZhihuImagePickerActivity.onCreate(ZhihuImagePickerActivity.java)
    at android.app.Activity.performCreate(Activity.java:6351)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1114)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2470)
    ... 9 more
kotlin.KotlinNullPointerException
    at com.qingmei2.rximagepicker_extension.entity.SelectionSpec$Companion.getInstance(SelectionSpec.java:0)
    at com.qingmei2.rximagepicker_extension_zhihu.ui.ZhihuImagePickerActivity.onCreate(ZhihuImagePickerActivity.java)
    at android.app.Activity.performCreate(Activity.java:6351)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1114)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2470)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577)
    at android.app.ActivityThread.access$1000(ActivityThread.java:166)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1414)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5619)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)

**Comment by qingmei2** [comment]
这个问题我看一下，能否提供复现的操作呢？

**Comment by diswy** [comment]
@qingmei2 这个主要也是友盟收集上来的BUG，感觉出现崩溃的概率比较高，这边暂时不知道如何复现，如果有用户反馈的上来我这边及时提交上来

**Comment by qingmei2** [comment]
@diswy 

这个是2.5.4的bug吗，还是2.5.3就有的问题呢？

**Comment by diswy** [comment]
@qingmei2 2.5.3就有该BUG，2.5.4依旧存在

**Comment by qingmei2** [comment]
@diswy 

谢谢你提供的信息，我会尝试尽快定位到问题并修复。

**Comment by kinling** [comment]
我用的2.5.1，刚看到友盟上也收集到相同的bug
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xybaby.lucky/com.xybaby.imagepicker.ui.ImagePickerActivity}: kotlin.KotlinNullPointerException
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3961)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:213)
    at android.app.ActivityThread.main(ActivityThread.java:8178)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
Caused by: kotlin.KotlinNullPointerException
    at com.qingmei2.rximagepicker_extension.entity.SelectionSpec$Companion.getInstance(SelectionSpec.kt:127)
    at com.xybaby.imagepicker.ui.ImagePickerActivity.onCreate(Native Method)
    at android.app.Activity.performCreate(Activity.java:8086)
    at android.app.Activity.performCreate(Activity.java:8074)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3755)
    ... 11 more
kotlin.KotlinNullPointerException
    at com.qingmei2.rximagepicker_extension.entity.SelectionSpec$Companion.getInstance(SelectionSpec.kt:127)
    at com.xybaby.imagepicker.ui.ImagePickerActivity.onCreate(Native Method)
    at android.app.Activity.performCreate(Activity.java:8086)
    at android.app.Activity.performCreate(Activity.java:8074)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3755)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3961)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:213)
    at android.app.ActivityThread.main(ActivityThread.java:8178)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by diswy** [comment]
@qingmei2 不知大哥有空排查么，后台一直有这个问题在上报，应该是一个空指针引发的

**Comment by Roben1016** [comment]
@qingmei2 这个问题复现很简单,在开发者模式中打开不保留活动, 然后打开图片选择的activity, 按home键, 然后重新返回APP就能重现, 是APP在相册页面被后台杀死后重新返回APP, 单例类SelectionSpec中的单例报空指针

**Comment by Roben1016** [comment]
@qingmei2 这个问题我这边复现过,但不是必现,在开发者模式中打开不保留活动, 然后打开图片选择的activity, 切换到其它应用, 然后重新返回APP偶尔重现, 是APP在相册页面被后台杀死后重新返回APP, 单例类SelectionSpec中的单例报空指针

**Comment by diswy** [comment]
这种有没有什么比较好的解决方案？

**Comment by zccguagua** [comment]
AndroidX项目使用2.5.6一点击就出现这个问题，后来仔细看了使用文档，使用3.0.0-beta02后可以正常使用
